- include_tasks: deploy.yml
  when: buildbot_role_mode == 'deployment'

- include_tasks: reconfigure.yml
  when: buildbot_role_mode == 'reconfiguration'

- include_tasks: restart.yml
  when: buildbot_role_mode == 'restart'
