---
- name: Upload master configuration file from template
  template:
    src: {{ item.src }}
    dest: {{ item.dest }}
    owner: root
    group: root
    mode: 0444
  with_items:
    - { src: "{{ buildbot_master_cfg_file_path }}", dest: "{{ main_folder }}/./volumes/buildbot-master/master.cfg" }

- name: Upload or render master extra files
  copy:
    src: "{{ item.path }}{{ item.file }}"
    dest: "{{ main_folder }}/volumes/buildbot-master/{{ item.file }}"
    owner: root
    group: root
    mode: 0444
  with_items:
    - "{{ buildbot_master_extra_files }}"

- name: Apply new Buildbot config
- docker_compose:
    project_src: "{{ main_folder }}"
    state: present
    build: yes
    services:
      - buildbot
      - worker
    restarted: true


